[package]
name = "rusty_present_parser"
version = "0.1.0"
authors = ["Chris Gatehouse <cgate2@pdx.edu>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
pkg-config = "0.3.15"
